### ISSUE TITLE
Hackintosh Support 

### ISSUE THREAD

**Issue by seanliu96** [zackelia/bclm#10]
Hi zackelia,

I am using Hackintosh on my T460s with v0.0.4, but I got the KeyNotFound(code: "BCLM") error.

Could you please tell me some details about how to check the SMC status from .kext files.

Thanks.

**Comment by seanliu96** [comment]
I think https://github.com/acidanthera/VirtualSMC should be the relevant file.

**Comment by zackelia** [comment]
It looks like if you used something like VirtualSMC, you would be able to use this project as long as it provides the bclm key (bfcl is optional). It is necessary though as the SMC is actual hardware in Mac computers.

**Comment by seanliu96** [comment]
It is interesting that I set the threshold in Windows 10 but that still works in MacOS.
