### ISSUE TITLE
support for Apple ARM M1

### ISSUE THREAD

**Issue by hkennyv** [zackelia/bclm#12]
Hey there,

I use your extension on both of my other MacBooks and just want to say great job. Simple and easy to use.

I just got an M1 MBA and would love to use it as well but am having some trouble..

So far, I've:

- installed homebrew natively under `/opt/homebrew`
- ran the following successfully:

```
brew tap zackelia/formulae
```

- but when i run:

```
sudo bclm write 72
```

i get the error:

```
sudo: unable to execute /opt/homebrew/bin/bclm: Bad CPU type in executable
```

Any pointers in the right direction? Happy to help get M1 support running with your package in any way :)

**Comment by hkennyv** [comment]
going to try building from source later today & i'll update 👍 

(i think the issue is the pre-built package on brew is not targeted for ARM)

**Comment by zackelia** [comment]
You're right that would would need to compile an ARM binary for it to even run. However, the M1 MacBooks don't have the SMC which is what this project relies on so you unfortunately won't be able to use it.

**Comment by peterlewis** [comment]
Hey @zackelia! Just for your information, [AlDente](https://github.com/davidwernhart/AlDente) has now released an update that supports Apple Silicon. Just wanted to let you know in case this was something you wanted to consider for `bclm`. Happy to take a stab at it, though my knowledge in this area is limited!

**Comment by hkennyv** [comment]
I completely agree with @peterlewis! If there's any way I could help test, run code, whatever on my M1 machine, I'd be very happy to do so. :)

**Comment by seamusdemora** [comment]
Any forward progress on an Apple Silicon version of `bclm`?

**Comment by zackelia** [comment]
See #20 for updates.

**Comment by seamusdemora** [comment]
Thanks... I shoulda' posted my question here instead of in #20 : 

Will this cover the M2 chip also?
