### ISSUE TITLE
Is it compatible with the new battery charging mechanism on Big Sur?

### ISSUE THREAD

**Issue by lucifer662607004** [zackelia/bclm#17]
Big Sur will only charge my computer to 80% until it feels necessary. 
What happens when setting BCLM to 60?

**Comment by lucifer662607004** [comment]
It will be locked at 63%.

I disabled battery optimising. because even myself don't know when will I use the MacBook, I don't think Big Sur will do.

**Comment by WillingAC** [comment]
> It will be locked at 63%.
> 
> I disabled battery optimising. because even myself don't know when will I use the MacBook, I don't think Big Sur will do.

You mean you tested it? The question would be closed then?
