### ISSUE TITLE
doesn't work on 2008 aluminum unibody Macbook

### ISSUE THREAD

**Issue by sdedalus1** [zackelia/bclm#18]
FYI, doesn't seem to work on my  2008 aluminum unibody Macbook (with patched OS 10.12.6 High Sierra):
`bclm read`
gives
`keyNotFound(code: "BCLM")`

`bclm read --version`
gives
`[0.0.4]`

Meanwhile, I also tried [OSX Battery Charge Limit](https://github.com/DevNulPavel/osx_battery_charge_limit) and it returned the error
```
ERROR: SMC out parse failed
valid "  BCLM  [ui8 ]  60 (bytes 3c)"
current "  BCLM  [    ]  no data"
```

**Comment by zackelia** [comment]
Intel Macs without the BCLM key are unsupported.
