### ISSUE TITLE
ERROR occur while install at Mac M1 machine

### ISSUE THREAD

**Issue by dachen139** [zackelia/bclm#19]
keyNotFound(code: "BCLM")

Please update BCLM to Mac M1 version, thanks so much.

**Comment by haiwencn** [comment]
I meet the same problem. Really need it on the new Mac!!!

**Comment by haiwencn** [comment]
Solved, please refer to this https://github.com/davidwernhart/AlDente

**Comment by actuallymentor** [comment]
> Solved, please refer to this https://github.com/davidwernhart/AlDente

This is not a solution, this is an alternative :)

I'd love to have this work on an M1.
