### ISSUE TITLE
support for mac os versions earlier than catalina

### ISSUE THREAD

**Issue by hkennyv** [zackelia/bclm#2]
Hey there,

Just wondering if this is possible. I didn't see anything in the README mentioning it, so I thought it couldn't hurt to ask

Cheers!

**Comment by hkennyv** [comment]
no problem! thank you for your work!

I have not run it yet. I can give it a shot in the next couple of days probably

**Comment by hkennyv** [comment]
so unfortunately, it seems like the answer to this is no. I'm unable to build your package on mojave because mojave doesn't support the xcode version required to use Swift 5.2! I'm stuck on Swift 5.1 unfortunately :(

**Comment by zackelia** [comment]
After a little research, it seems that while you won't be able to build my project as is, you might be able to run a copy of bclm that I've built. Would you mind downloading bclm from the releases section and using the release instructions? If that doesn't work I'll keep looking though!

**Comment by hkennyv** [comment]
thanks @zackelia! i'm able to run it!

```
khuynh@kmbp:~/Downloads $ sudo ./bclm write 80
khuynh@kmbp:~/Downloads $ sudo ./bclm read
80
```

My battery is pretty much full right now so i'll continue to use it so i can verify it's working as expected

**Comment by hkennyv** [comment]
and it seems to work! thanks so much for your work!

**Comment by zackelia** [comment]
Glad it's working now! I've updated the README accordingly for future users.
