### ISSUE TITLE
error of build, cannot convert value

### ISSUE THREAD

**Issue by prorang** [zackelia/bclm#24]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/26851600/171996935-b6ebf097-b1a4-4b7f-81f4-dabb1bc3e0de.png">
Apple m1 macbook pro 13
1. download zip
2. cd blm-master
3. swift build

**Comment by zackelia** [comment]
Resolved in [f240f37](https://github.com/zackelia/bclm/commit/f240f37f99757fcc0b8f38ecab0d68de26665aef).
