### ISSUE TITLE
Apple Silicon macOS Ventura - persist seems to be misbehaving

### ISSUE THREAD

**Issue by seamusdemora** [zackelia/bclm#33]
I've "installed" via the `sudo cp bclm /usr/local/bin` method.
I've set the  charge level: `sudo bclm write 80` 
I've confirmed the charge level: `bclm read` ==> `80`
I've set persistence: `sudo bclm persist` 
I've confirmed (using `LaunchControl`) that the `com.zackelia.bclm.plist` is loaded & running: `/usr/local/bin/bclm write 80`
I disabled Apple's native "Optimized Battery Charging" before installing `bclm` (REF #32 )

Earlier tonight, I had to remove my Mac from the charger for a while in the lab. The charge level had declined to `77%` during that time. When I plugged the charger in again, I expected it to charge up to `80%` - but it did not do this. Instead, hours later, it is still sitting at `77%`.

Is this the expected behavior? What should I do to return the "persistence" to the set value of `80%`??

---

**UPDATE/FWIW:**  I've discovered that following a **Restart**, the `bclm`-controlled battery charging to the 80% level is resumed.  

You're missing something here, dude.

**Comment by zackelia** [comment]
Not seeing this issue on my hardware. On Apple Silicon, `bclm` either writes 80 or 100 to the `CHWA` key and the firmware takes it from there. Not sure how I'm missing something.

**Comment by lslqtz** [comment]
From a technical point of view, on Apple Silicon, the program is only responsible for writing the CHWA value, and the specific charging logic is determined by Apple firmware.

This SMC key is used for Apple's Optimized Battery Charging, so if this issue occurs, then I speculate that there is only one possibility: Apple designed this value to be used with a loop check or a program that triggers periodically.

Obviously, the program was not designed to do this, so it's not the program's fault, nor Apple's.

Of course, maybe a workaround can be implemented, but it still needs to be observed what exactly is causing the problem

**Comment by seamusdemora** [comment]
> From a technical point of view, on Apple Silicon, the program is only responsible for writing the CHWA value, and the specific charging logic is determined by Apple firmware.

Oh good grief...  the program is responsible for "working" - or at least behaving rationally. Unfortunately, `bclm` does neither. So - make your excuses, put a very fine point on it - but don't start making up s**t about what the program is responsible for.

**Comment by 18Song** [comment]
@seamusdemora I'm in a similar situation, but I didn't turn off "Optimized Battery Charging" and I didn't restart, I just unplugged it at night when I was resting, and it's gone from 80 to 77 in the last three days, with no sign of charging upwards!

**Comment by 18Song** [comment]
@seamusdemora 74，started charging.
![image](https://github.com/zackelia/bclm/assets/73453430/05d7d25d-adb9-41bd-afd9-db9d34758712)

**Comment by 18Song** [comment]
@seamusdemora https://support.apple.com/en-us/108055#:~:text=About%2080%25%20Limit%20with%20iPhone%2015%20models
Referring to iphone's charging strategy, I think mac's charging strategy is the same as iphone's. And, on iphone, optimized battery charging and charging to 80% is an either/or, so it makes more sense to turn off optimized battery charging on mac after setting the threshold to 80 using bclm.
