### ISSUE TITLE
how to enable bclm directly from macOS?

### ISSUE THREAD

**Issue by checktext00** [zackelia/bclm#43]
Hi, I realize this isn't an issue for this app, but I've looked online and couldn't find this answer

How can I write the BCLM value to the SMC without using any 3rd party apps? Are there a set of terminal commands that will achieve the same thing? (And also allow reading the value, and reading/writing BFCL)

Thanks

**Comment by zackelia** [comment]
If there were native binaries to do the same thing, `bclm` would have no reason to exist.

`bclm` (and probably many other tools) utilize [SMCKit](https://github.com/beltex/SMCKit) which interacts with the SMC via private APIs.

**Comment by checktext00** [comment]
thanks
