### ISSUE TITLE
On a 2017 Intel MacBook Pro, how to make the battery level drop from 100 to 80?

### ISSUE THREAD

**Issue by JustFavor** [zackelia/bclm#44]
During my use of blcm, I have been very confused about how to make my battery level drop from 100 to 80. It seems to only pause charging. I really need a way to disconnect the power supply from the battery adapter on an Intel MacBook Pro. Do you have any solutions? I would be very grateful.

**Comment by zackelia** [comment]
> It seems to only pause charging

Yes, that's all bclm will do. I don't have any other solutions to what you're looking for.
