### ISSUE TITLE
Display correct charge indicator LED on Magsafe charger

### ISSUE THREAD

**Issue by godly-devotion** [zackelia/bclm#5]
On older MacBooks that use the MagSafe charger, the LED turns green if it has finished charging. Just changing the BCLM value does not influence the MagSafe LED color.
There is a value in the SMC called `BFCL` (Battery Final Charge Level) that holds the value for when the LED color should change to green. By default, for the machines that have this value, the value is 5 less than the `BCLM`. So for example, if you were to set the `BCLM` to 65%, then you would set the `BFCL` to 60%. This follows what Apple does because its default value is `5f`, or 95%.
Please add this option for changing this value as well.

PS I've added this ability in https://github.com/godly-devotion/charge-limiter as well for reference.

**Comment by zackelia** [comment]
@godly-devotion Thanks for letting me know about this, I was wondering if this option existed! It is now default behavior in `bclm` v0.0.3 to set the `BFCL` value accordingly.
