### ISSUE TITLE
Unable to install using Brew

### ISSUE THREAD

**Issue by GimmiGoose** [zackelia/bclm#50]
Hi, I keep getting this error 
<img width="682" alt="image" src="https://github.com/user-attachments/assets/7ce83b01-33de-4866-a7ae-7330b6bb3021">

**Comment by zackelia** [comment]
Those commands look right and I'm not able to reproduce your issue. Maybe try troubleshooting brew? https://docs.brew.sh/Troubleshooting

**Comment by GimmiGoose** [comment]
I reinstalled it everything including Homebrew, but now I am getting the same error that caused me to reinstall everything

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/7b9d3d73-53df-4c8a-9e45-31fb8a0fb562">

**Comment by zackelia** [comment]
Not sure what happened with your `brew` earlier but it looks fine now. The issue you're currently seeing is #49.
