### ISSUE TITLE
BCLM not working macOS Sequoia 

### ISSUE THREAD

**Issue by arsildo** [zackelia/bclm#57]
keyNotFound(code: "CHWA")

![image](https://github.com/user-attachments/assets/8490aeb2-a7a5-47b4-bb3e-abe743bbc49e)

**Comment by erdong01** [comment]
I also encountered

**Comment by thaff786** [comment]
https://github.com/lslqtz/bclm_loop/tree/main

This fork of BCLM is working is Sequoia

**Comment by zackelia** [comment]
#49
