### ISSUE TITLE
keyNotFound(code: "BFCL")

### ISSUE THREAD

**Issue by bmansvk** [zackelia/bclm#9]
When running bclm v.0.0.3 there is an following error output:

sudo bclm write 75
keyNotFound(code: "BFCL")

Running on USB-C Macbook Air 2019. It seems that Macbooks with USB-C charging doesn't have BFCL in SMC.

BTW: Thank you for this great and dead simple tool.

**Comment by zackelia** [comment]
Fixed in v0.0.4 now, can you tell I don't have a USB-C Mac? :)

Also thank you for the kind words! That was my exact goal when creating this.

**Comment by seanliu96** [comment]
Hi zackelia,

I am using Hackintosh on my T460s with v0.0.4, but I got the KeyNotFound(code: "BCLM") error.
